/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import mininet.Adult;
import mininet.Person;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yifan ZHANG s3615625
 */
public class UpdateProfile extends javax.swing.JFrame 
{   
    DisplayProfile dp;
    Person p;

    /**
     * Creates new form UpdateProfile
     */
    public UpdateProfile(DisplayProfile dp) 
    {
        initComponents();
        
        this.dp = dp;
        
        p = MiniNet.driver.getPersonByName(dp.getJLABName().getText());
        
        if(p instanceof Adult)
        {
            this.jLabFather.setVisible(false);
            this.jLabMother.setVisible(false);
            this.jLABFN.setVisible(false);
            this.jLABMN.setVisible(false);
        }
        
        this.jLName.setText(dp.getJLABName().getText());
        //We only allow the user to change a person's
        this.jTFPhoto.setText(p.getPhotoPath());
        //photoPath and his/her status
        this.jTFStatus.setText(dp.getJLABStatus().getText());
        
        this.jLGender.setText(dp.getJLABGender().getText());
        
        this.jLAge.setText(dp.getJLABAge().getText());
        //along with his/her residing state
        this.jCBState.setSelectedItem(dp.getJLABState().getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jMenu = new javax.swing.JMenu();
        jLabName = new javax.swing.JLabel();
        jLabStatus = new javax.swing.JLabel();
        jLabGender = new javax.swing.JLabel();
        jLabAge = new javax.swing.JLabel();
        jLabState = new javax.swing.JLabel();
        jTFStatus = new javax.swing.JTextField();
        jCBState = new javax.swing.JComboBox<>();
        jBUpdate = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLName = new javax.swing.JLabel();
        jLGender = new javax.swing.JLabel();
        jLAge = new javax.swing.JLabel();
        jLabPhoto = new javax.swing.JLabel();
        jTFPhoto = new javax.swing.JTextField();
        jLabFather = new javax.swing.JLabel();
        jLabMother = new javax.swing.JLabel();
        jLABFN = new javax.swing.JLabel();
        jLABMN = new javax.swing.JLabel();

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane.setViewportView(jList);

        jMenu.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabName.setText("Name:");

        jLabStatus.setText("Status:");

        jLabGender.setText("Gender:");

        jLabAge.setText("Age:");

        jLabState.setText("State:");

        jCBState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA" }));

        jBUpdate.setText("Update");
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jLabPhoto.setText("Photo Path: ");

        jLabFather.setText("Father:");

        jLabMother.setText("Mother:");

        jLABMN.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(302, 302, 302))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabGender)
                            .addGap(311, 311, 311)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabStatus)
                            .addComponent(jLabFather)
                            .addComponent(jLabMother))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLABFN, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLABMN, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLGender, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabState, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabAge, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLAge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCBState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabPhoto)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 94, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabName)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPhoto)
                    .addComponent(jTFPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLGender, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLAge, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabState)
                    .addComponent(jCBState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabFather)
                    .addComponent(jLABFN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLABMN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabMother))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancel)
                    .addComponent(jBUpdate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed
        
        String message = "";
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("").getImage()
                    .getScaledInstance(dp.getJLABImage().getWidth(), dp.getJLABImage().getHeight(), Image.SCALE_SMOOTH));
        
        dp.getJLABImage().setIcon(new ImageIcon(this.jTFPhoto.getText() ));
        p.setPhotoPath(this.jTFPhoto.getText());
            
        dp.getJLABStatus().setText(this.jTFStatus.getText());
        p.setStatus(this.jTFStatus.getText());
        dp.getJLABState().setText(this.jCBState.getSelectedItem().toString());
        p.setState(this.jCBState.getSelectedItem().toString());
        
        message = "Successfully updated the selected person's profile !";
        
        
        JOptionPane.showMessageDialog(null, message ,"Message", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_jBUpdateActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        
        this.jTFPhoto.setText(p.getPhotoPath());
        
        this.jTFStatus.setText(dp.getJLABStatus().getText());
        
        this.jCBState.setSelectedItem(dp.getJLABState().getText());
    }//GEN-LAST:event_jBCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JComboBox<String> jCBState;
    private javax.swing.JLabel jLABFN;
    private javax.swing.JLabel jLABMN;
    private javax.swing.JLabel jLAge;
    private javax.swing.JLabel jLGender;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLabAge;
    private javax.swing.JLabel jLabFather;
    private javax.swing.JLabel jLabGender;
    private javax.swing.JLabel jLabMother;
    private javax.swing.JLabel jLabName;
    private javax.swing.JLabel jLabPhoto;
    private javax.swing.JLabel jLabState;
    private javax.swing.JLabel jLabStatus;
    private javax.swing.JList<String> jList;
    private javax.swing.JMenu jMenu;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTFPhoto;
    private javax.swing.JTextField jTFStatus;
    // End of variables declaration//GEN-END:variables
}
